[general]
import = [
    "./theme.toml",
    "./font.toml",
    "./font-size.toml"
]

[env]
TERM = "xterm-256color"

[font]
offset = { y = 4 }

[terminal]
# shell = { program = "wsl", args = ["~", "-e", "zellij"] }
shell = { program = "zellij" }

[window]
blur = true
decorations = "None"
dynamic_padding = true
opacity = 1
padding = { x = 0, y = 0 }
option_as_alt = "Both"
startup_mode = "Fullscreen"

[debug]
persistent_logging = true
log_level = "Debug"
print_events = true
