[font]
normal = { family = "DankMono Nerd Font", style = "Regular" }
bold = { family = "DankMono Nerd Font", style = "Bold" }
italic = { family = "DankMono Nerd Font", style = "Italic" }
#normal = { family = "FiraCode Nerd Font", style = "Regular" }
#bold = { family = "FiraCode Nerd Font", style = "Bold" }
#italic = { family = "FiraCode Nerd Font", style = "Italic" }
